import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { NameStoreProvider } from "@/providers/name-store-provider";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NameStoreProvider>
          <Navbar />
          {children}
        </NameStoreProvider>
      </body>
    </html>
  );
}
